[Feat/#267] 관리자페이지 글감설정 뷰 & 공통 페이지네이션
Mile-Writings/Mile-Client pull request #270
Opened 2024-03-24 09:09 UTC by moondda

### ✨ 해당 이슈 번호 ✨

### todo 

- [ ] checklist!

## 📌 내가 알게 된 부분

- 

## 📌 질문할 부분 

-

## 📌스크린샷(선택)

2024-03-26 08:45 UTC, se0jinYoon requested changes
유틸 빼고 일단 달아뒀슴다 !!!!
페이지네이션 / msw 잘 적용한 듯 해서 대견하네유 ..

2024-03-26 08:45 UTC, se0jinYoon commented on src/components/commons/Pagenation.tsx
> +const Pagenation = ({ count, allocatedCount }: { count: number; allocatedCount: number }) => {
p1) 요기 Pagenation props type interface로 정의해서 사용하는 컨벤션 적용해주세용 !

2024-03-26 08:45 UTC, se0jinYoon commented on src/components/commons/Pagenation.tsx
> +      {activePage != 1 && (
p1) !== 으로 타입체킹까지 해주기!

2024-03-26 08:45 UTC, se0jinYoon commented on src/components/commons/Pagenation.tsx
> +          style={{ cursor: 'pointer' }}
p3) 여기 styled-component안쓰고 inline-style로 적용한 이유가 있을까요 ?

2024-03-26 08:45 UTC, se0jinYoon commented on src/components/commons/Pagenation.tsx
> +          key={index + 1}
p3) key 값을 index+1로 한 이유가 뭘까요?

2024-03-26 08:45 UTC, se0jinYoon commented on src/main.tsx
> +  // eslint-disable-next-line no-undef
p2) 이거 왜 넣은거죠 !!

2024-03-26 08:45 UTC, se0jinYoon commented on src/main.tsx
> +});
p4) 선생님 여기 로직 좀 설명해주실 수있나요 저 MSW 처음봐서 이해 못하는 중

2024-03-26 08:45 UTC, se0jinYoon commented on src/pages/admin/EachTopic.tsx
> +const EachTopic = ({ data }: { data: AdminTopicPropTypes }) => {
p3) 여기 네이밍이 props가 아닌 data로 만들어둔 이유가 있을까요?

2024-03-26 08:45 UTC, se0jinYoon commented on src/pages/admin/RenderAdminContent.tsx
>  const RenderAdminContent = ({ admin }: { admin: 'topic' | 'member' | 'groupInfo' }) => {
p1) 여기도 props type interface로 지정하는 컨벤션 적용해주세요 !!

2024-03-26 08:45 UTC, se0jinYoon commented on src/pages/admin/RenderAdminContent.tsx
>  const RenderAdminContent = ({ admin }: { admin: 'topic' | 'member' | 'groupInfo' }) => {
여기는 유니온으로 이어져있으니까 interface말고 type으로 만들어서 해도 될듯?

2024-03-26 08:45 UTC, se0jinYoon commented on src/pages/admin/RenderAdminContent.tsx
p3) renderAdminContent랑 TopicAdmin이라는 컴포넌트 명이 잘 와닿지 않는데 어떤 걸 고려해서 이렇게 네이밍한 건지 알 수 있을까요 ?!

2024-03-26 08:45 UTC, se0jinYoon commented on src/pages/admin/apis/fetchAdminData.ts
p2) adminData가 여러가지이니까 파일명도 fetchAdminTopic과 같이 바꿔도 좋을 거 같아요!

2024-03-26 08:45 UTC, se0jinYoon commented on src/utils/PageNumber.tsx
> +}) => {
p1 ) 여기도 prop type interface 컨벤션!

2024-03-29 15:22 UTC, namdaeun commented on src/utils/Pagenation.tsx
> +          style={{ cursor: 'pointer' }}
P2: 인라인 스타일 보다 스타일 컴포넌트에서 정의해주는 게 코드의 재사용성 면에서 더 좋을 것 같다는 생각입니다!

2024-03-29 15:29 UTC, namdaeun commented on src/mocks/handler.ts
> +    // const moimId = params.moimId;
P3: 안 쓰이는 코드라면 지워주는 게 좋을 것 같습니다!

2024-03-29 15:33 UTC, namdaeun commented on src/pages/admin/TopicAdmin.tsx
> +      {data && data.topicCount && <Pagenation count={data.topicCount} allocatedCount={5} />}
오호 이렇게 사용하면 되는 군요 !! 굿굿

2024-03-29 15:45 UTC, namdaeun commented on src/utils/countPage.ts
> +      resultArray.push(allocatedCount * (chunk - 1) + i);
P3: 요 resultArray가 어떤 값을 담는 배열인지 설명 부탁드려도 될까요? 배열 이름을 그 역할을 담게 이름을 변경해도 좋을 것 같아요!

2024-03-29 15:48 UTC, namdaeun approved these changes
언니 고생많았어 !! 👍👍✨

2024-04-09 11:24 UTC, se0jinYoon approved these changes
저기 이해 안 간 부분만 대답해주세요 ! 로직은 구웃

2024-04-09 11:24 UTC, se0jinYoon commented on src/utils/countPage.ts
> +  const pageCount = Math.ceil(totalCount / allocatedCount);
[p5] pr에서 allocatedCount가 한 묶음당 배열수라고 했는데, 한 묶음당 배열 수가 동일하지 않지 않나요 ? 
예를들어 [1,2,3,4,5] , [6,7,8,9,10], [11,12] 면 5,5,2가 되는 거 아닌지 ? (이해부족이슈)

2024-04-09 11:24 UTC, se0jinYoon commented on src/utils/countPage.ts
> +    resultArray[resultArray.length - 1] === pageArray[pageArray.length - 1] ? false : true;
p3) 배열의 가장 마지막값을 확인하고싶다면 .at(-1)을 사용해도 된답니다
```suggestion
    resultArray.at(-1) === pageArray.at(-1) ? false : true;
```

2024-04-09 17:20 UTC, ljh0608 approved these changes
Good

2024-04-09 17:20 UTC, ljh0608 commented on src/components/commons/Pagenation.tsx
> +      {activePage != 1 && (
p1)필수

2024-04-09 17:20 UTC, ljh0608 commented on src/pages/admin/EachTopic.tsx
> +`;
p2) 시맨틱태그 적용해주세요! 이 위도 article로 활용할 수 있을 것 같아요~

2024-04-09 17:20 UTC, ljh0608 commented on src/utils/countPage.ts
> +      resultArray.push(allocatedCount * (chunk - 1) + i);
p4) 선언형 프로그래밍을 지향해야하기 때문에 for문을 사용하면 안된다 라고 코멘트를 남기려 했는데 
``` 
const resultArray = Array.from({ length: 5 }, (_, index) => allocatedCount * (chunk - 1) + (index + 1))
  .filter(value => value <= pageArray[pageArray.length - 1] && value > 0);
```
하지만 선언형 프로그래밍이 항상 "더 나은" 접근 방법이라고 할 수는 없습니다. 성능이 중요한 상황에서는 for 루프가 Array 메서드보다 빠를 수 있으며, 때로는 절차적 코드가 더 직관적일 수도 있습니다. 코드의 명확성, 유지 보수성, 성능 요구 사항 등을 고려하여 가장 적합한 접근 방식을 선택해야 합니다.
라고 하네요 참고해주세요~

2024-04-10 12:13 UTC, merged